Add `CropOptions`
benjajaja/ratatui-image pull request #27
Opened 2024-06-26 22:48 UTC by dzfrias

This allows the user to decide which side of the image should be cropped when resizing to fit the containing `Rect`. This is a breaking change, and let me know if the API is okay. I could swap the boolean `clip_bottom` and `clip_right` values with enums, if you want!

I could also work on an example, if necessary. I tested it the project I need it for and it works, but if you want something more robust I can definitely work on that.

2024-07-01 09:13 UTC, benjajaja requested changes
Thanks! It's really cool to make the clipping configurable.

I would prefer to switch the bools to default to `false`, so switching the naming from bottom->top and right->left. Perhaps in the future it could be enums, something like `vertical_align: Left | Center | right`. But we can leave that for later, if `Center` would actually be implemented.

The substractions must be safe against overflow.

2024-07-01 09:13 UTC, benjajaja commented on src/lib.rs
> +                    source.image.height() - height
```suggestion
                    source.image.height().saturating_sub(height)
```

2024-07-01 09:13 UTC, benjajaja commented on src/lib.rs
> +                    source.image.width() - width
```suggestion
                    source.image.width().saturating_sub(width)
```

2024-07-01 09:16 UTC, benjajaja commented
closes #26

2024-07-01 13:57 UTC, dzfrias commented
Thanks for the review! Changes implemented.

2024-07-02 11:24 UTC, benjajaja approved these changes

2024-07-02 11:24 UTC, merged

2024-07-02 11:29 UTC, benjajaja commented
@dzfrias published to crates.io in 1.0.2

2024-07-02 19:41 UTC, dzfrias commented
Awesome, thanks!